### ISSUE TITLE
Path issues on unix-like operating systems

### ISSUE THREAD

**Issue by Michae1Weiss** [Glebych-deb/citiesgameproject#1]
Hey!

------
**System information**
* OS Platform and Distribution:  Linux Ubuntu 20.04.2
* Python version: Python 3.8.10

------
**Describe the problem**

If i try to run a desktop application on unix-like systems, an error appears: 
`Executed file: desktop/main.py`
```bash
Traceback (most recent call last):
  File "/home/mykhailo/citiesgameproject/desktop/main.py", line 21, in <module>
    bg_img=PhotoImage(file=f"images\\3.png")  # doesn't work on Linux
  File "/usr/lib/python3.8/tkinter/__init__.py", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "images\3.png": no such file or directory
```
------

**Possible solution:**

`File: desktop/main.py`
```python
from pathlib import Path
...
# root.iconbitmap(f"images\\city.ico")  # doesn't work on Linux
root.iconbitmap(Path("images", "city.ico"))  # generate path for current operation system
...
# bg_img=PhotoImage(file=f"images\\3.png")  # doesn't work on Linux
bg_img=PhotoImage(file=Path("images", "3.png"))  # generate path for current operation system
```

`File: desktop/sound.py`
```python
from pathlib import Path
...
# s_catch = pygame.mixer.Sound(f'music\\sample.mp3')  # doesn't work on Linux
s_catch = pygame.mixer.Sound(Path("music", "sample.mp3"))  # generate path for current operation system
```

`File: desktop/load.py`
```python
from pathlib import Path
...
# con = sqlite3.connect(f'Temp\\example.db')  # doesn't work on Linux
con = sqlite3.connect(Path('Temp', 'example.db'))  # generate path for current operation system
```

**Comment by Capral-coder** [comment]
Добрый день! У нас проблема в том что мы не можем несколько файлов закинуть в один exe файл. А если делать exe с главного файла. Ничего не работает.
